---
- name: V-222983 | Set Tomcat account shell to nologin
  ansible.builtin.user:
    name: "{{ tomcat9_stig_user }}"
    shell: /usr/sbin/nologin
  tags: [V-222983]

- name: V-222949 | Create systemd override directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ tomcat9_stig_service_name }}.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: [V-222949]

- name: V-222949 | Set Tomcat service UMask
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ tomcat9_stig_service_name }}.service.d/10-stig-umask.conf"
    owner: root
    group: root
    mode: "0644"
    content: |
      [Service]
      UMask={{ tomcat9_stig_umask }}
  notify: Reload systemd
  tags: [V-222949]
